matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "12"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - stage: "WebPack"
      os: osx
      env:
        - WebPack="iOS"
      osx_image: xcode10.2
      language: node_js
      node_js: "12"
      jdk: oraclejdk8
      before_install:
        - pip install --upgrade pip
        - pip install --user --upgrade matplotlib
        - pip install six
      before_script: pod repo update
      script: cd demo && npm run build.plugin && npm i && tns build ios --env.uglify
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install: nvm install 12
      script: cd demo && npm run build.plugin && npm i && tns build android --env.uglify --env.snapshot
    - stage: "Tests"
      os: osx
      env:
        - iOS="UnitTests"
      osx_image: xcode10.2
      language: node_js
      node_js: "12"
      jdk: oraclejdk8
      before_script:
          - ios-sim start --devicetypeid "iPhone-8-Plus, 12.0"
      before_install:
          - pip install --upgrade pip
          - pip install --user --upgrade matplotlib
          - pip install six
          - npm install -g ios-sim
      script:
          - cd src && npm i && npm run tsc && npm run tslint && cd ../demo && tns build ios && tns test ios --justlaunch
    - language: android
      os: linux
      env:
        - Android="UnitTests"
      jdk: oraclejdk8
      before_install: nvm install 12
      before_script:
          - echo no | android create avd --force -n test -t android-28 -b x86
          - emulator -avd test -no-audio -no-window &
          - android-wait-for-emulator
      script:
          - cd src && npm i && npm run tsc && npm run tslint && cd ../demo && tns build android
          - travis_wait travis_retry tns test android --justlaunch

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - sys-img-x86-google_apis-28

install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
